name: sentiment-analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - attrs=20.2.0
  - beautifulsoup4=4.9.1
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1
  - eli5=0.10.1
  - flask=1.1.2
  - graphviz=2.38.0
  - idna=2.10
  - intel-openmp=2020.2
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - joblib=0.16.0
  - libiconv=1.15
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.5.2
  - markupsafe=1.1.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.5.0
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1h
  - pandas=1.1.1
  - pandas-datareader=0.9.0
  - pip=20.2.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.6.5
  - python-dateutil=2.8.1
  - python-graphviz=0.14.2
  - python_abi=3.6
  - pytz=2020.1
  - requests=2.24.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - selenium=3.141.0
  - setuptools=49.6.0
  - simplejson=3.17.2
  - singledispatch=3.4.0.3
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlalchemy=1.3.19
  - tabulate=0.8.7
  - threadpoolctl=2.1.0
  - ujson=3.2.0
  - urllib3=1.25.10
  - werkzeug=1.0.1
  - wheel=0.35.1
  - zlib=1.2.11
